# -*- coding: utf-8 -*-
"""U1P1 - Medición empírica de complejidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTvOrNBraF2O6Hg5UIrccy9rL1u4D2gq
"""

# Practica 1 - Medicion empirica de complejidad
# Analisis de Algoritmos
# Uziel Hashid Ibarra Rivas
# https://github.com/UzielIbarra/Practica1-Complejidad.git
# Lenguaje: Python 3

import time
import random

def recorrido_simple(lista):
    total = 0
    for x in lista:
        total += x
    return total

def doble_ciclo(lista):
    contador = 0
    for i in range(len(lista)):
        for j in range(len(lista)):
            contador += lista[i] * lista[j]
    return contador

def experimento():
    tamanios = [1000, 5000, 1000, 20000]
    print("Tamano | Recorrido simple (s) | Doble ciclo (s)")
    print("-" * 55)

    for n in tamanios:
        datos = [random.randint(1, 100) for _ in range(n)]

        # Medir tiempo recorrido simple
        inicio = time.time()
        recorrido_simple(datos)
        t1 = time.time() - inicio

        # Medir tiempo doble ciclo
        inicio = time.time()
        doble_ciclo(datos)
        t2 = time.time() - inicio

        print(f"{n:6d} | {t1:20.6f} | {t2:15.6f}")

if __name__ == "__main__":
    experimento()